const firebase = window.parent.INTERCOL_FIREBASE;
const form = document.querySelector("#retiredForm"), list = document.querySelector("#recordList"), search = document.querySelector("#searchInput"), filter = document.querySelector("#statusFilter");
let records = [], editingId = "", stopSync = null, advisor = null;
const today = () => { const d = new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0,10); };
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const labelStatus = value => ({pendiente:"Pendiente", realizado:"Realizado", cancelado:"Cancelado"}[value] || "Pendiente");
function normalize(item){ return { id:item.id, ...item, nombre:String(item.nombre||""), cedula:String(item.cedula||""), fechaAgendado:String(item.fechaAgendado||""), estado:item.estado||"pendiente", direccion:String(item.direccion||""), barrio:String(item.barrio||""), rb:String(item.rb||""), descripcion:String(item.descripcion||"") }; }
function setStatus(text,error=false){ const node=document.querySelector("#formStatus"); node.textContent=text; node.style.color=error?"#dc2626":""; }
function resetForm(){ form.reset(); form.elements.recordId.value=""; form.elements.fechaAgendado.value=today(); editingId=""; document.querySelector("#formTitle").textContent="Agendar retiro"; document.querySelector("#saveButton").textContent="Guardar retiro"; document.querySelector("#cancelEdit").hidden=true; }
function beginEdit(record){ editingId=record.id; Object.entries(record).forEach(([key,value])=>{if(form.elements[key])form.elements[key].value=value;}); form.elements.recordId.value=record.id; document.querySelector("#formTitle").textContent="Editar retiro"; document.querySelector("#saveButton").textContent="Guardar cambios"; document.querySelector("#cancelEdit").hidden=false; setStatus("Editando a "+record.nombre+"."); form.elements.nombre.focus(); }
function render(){ const term=search.value.trim().toLowerCase(), wanted=filter.value; const rows=records.filter(record=>(!wanted||record.estado===wanted)&&(!term||Object.values(record).some(value=>String(value).toLowerCase().includes(term)))).sort((a,b)=>String(a.fechaAgendado).localeCompare(String(b.fechaAgendado))); document.querySelector("#recordCount").textContent=rows.length; list.replaceChildren(); rows.forEach(record=>{ const card=document.createElement("article"); card.className="record-card"; card.innerHTML=`<div><div class="record-top"><strong class="record-name">${esc(record.nombre)}</strong><span class="status-badge status-${esc(record.estado)}">${labelStatus(record.estado)}</span></div><div class="record-meta">Cédula ${esc(record.cedula)} · ${esc(record.fechaAgendado||"Sin fecha")} · ${esc(record.barrio||"Sin barrio")} · ${esc(record.rb||"Sin RB")}</div><div class="record-meta">${esc(record.direccion||"Sin dirección")}</div>${record.descripcion?`<div class="record-description">${esc(record.descripcion)}</div>`:""}</div><div class="record-actions"><button type="button" data-edit="${esc(record.id)}">Editar</button><button type="button" data-delete="${esc(record.id)}" class="delete">Eliminar</button></div>`; list.append(card); }); document.querySelector("#emptyState").hidden=rows.length>0; window.parent.postMessage({type:"INTERCOL_SECTION_RESIZE",height:document.documentElement.scrollHeight},"*"); }
form.addEventListener("submit",async event=>{ event.preventDefault(); const data=Object.fromEntries(new FormData(form).entries()); if(!data.nombre||!data.cedula||!data.fechaAgendado){setStatus("Completa nombre, cédula y fecha.",true);return;} data.asesorUid=advisor.uid; data.asesor=advisor.nombre; const button=document.querySelector("#saveButton"); button.disabled=true; try{ if(editingId) await firebase.updateRetiredRecord(editingId,data); else await firebase.createRetiredRecord(data); setStatus(editingId?"Retiro actualizado.":"Retiro guardado."); resetForm(); }catch(error){console.error(error);setStatus(error.code==="permission-denied"?"Firebase bloqueó esta operación. Revisa el permiso Retirados del rol.":"No se pudo guardar el retiro.",true);}finally{button.disabled=false;} });
document.querySelector("#cancelEdit").addEventListener("click",()=>{resetForm();setStatus("");}); search.addEventListener("input",render); filter.addEventListener("change",render); document.querySelector("#clearSearch").addEventListener("click",()=>{search.value="";filter.value="";render();}); list.addEventListener("click",async event=>{ const edit=event.target.closest("[data-edit]"), remove=event.target.closest("[data-delete]"); if(edit){beginEdit(records.find(item=>item.id===edit.dataset.edit));return;} if(remove&&confirm("¿Eliminar este retiro?")){try{await firebase.deleteRetiredRecord(remove.dataset.delete);}catch(error){setStatus("No se pudo eliminar el retiro.",true);}} });
window.addEventListener("message",event=>{if(event.data?.type!=="INTERCOL_THEME")return;Object.entries(event.data.variables||{}).forEach(([name,value])=>document.documentElement.style.setProperty(name,value));document.documentElement.dataset.theme=event.data.theme||"light";}); window.parent.postMessage({type:"INTERCOL_SECTION_READY"},"*"); new ResizeObserver(()=>window.parent.postMessage({type:"INTERCOL_SECTION_RESIZE",height:document.documentElement.scrollHeight},"*")).observe(document.documentElement);
async function start(user,profile){ try{ advisor={uid:user.uid,nombre:profile?.asesor||user.email||"Asesor"}; document.querySelector("#syncStatus").textContent="Sincronizado"; stopSync=firebase.subscribeRetiredRecords(advisor.uid,items=>{records=items.map(normalize);render();},()=>{document.querySelector("#syncStatus").textContent="Error de sincronización";}); resetForm(); }catch(error){console.error(error);document.querySelector("#syncStatus").textContent="Sin acceso";setStatus("No se pudo cargar esta sección.",true);} }
window.addEventListener("message",event=>{if(event.data?.type!=="INTERCOL_AUTH_STATE")return;if(stopSync){stopSync();stopSync=null;}if(event.data.user&&event.data.profile)start(event.data.user,event.data.profile);else{advisor=null;records=[];render();document.querySelector("#syncStatus").textContent="Inicia sesión";setStatus("Inicia sesión para cargar tus retiros.",true);}});
